services:
  paper:
    build: .
    ports:
      - "25565:25565"
    volumes:
      - /home/minecraft/mc-server:/data
    user: "1001:1001"
    environment:
      EULA: "TRUE"
      JAVA_OPTS: "-Xms1024m -Xmx8G"
      MOTD: "Official Faclab Minecraft Server"
      SERVER_PORT: "25565"
      DIFFICULTY: "hard"