#!/bin/sh
MC_BASE=/opt/minecraft
SERVER_PATH=$MC_BASE/server.jar

export ACCEPTS_TRANSFERS=${ACCEPTS_TRANSFERS:-false}
export ALLOW_FLIGHT=${ALLOW_FLIGHT:-false}
export ALLOW_NETHER=${ALLOW_NETHER:-true}
export BROADCAST_CONSOLE_TO_OPS=${BROADCAST_CONSOLE_TO_OPS:-true}
export BROADCAST_RCON_TO_OPS=${BROADCAST_RCON_TO_OPS:-true}
export DEBUG=${DEBUG:-false}
export DIFFICULTY=${DIFFICULTY:-easy}
export ENABLE_COMMAND_BLOCK=${ENABLE_COMMAND_BLOCK:-false}
export ENABLE_JMX_MONITORING=${ENABLE_JMX_MONITORING:-false}
export ENABLE_QUERY=${ENABLE_QUERY:-false}
export ENABLE_RCON=${ENABLE_RCON:-false}
export ENABLE_STATUS=${ENABLE_STATUS:-true}
export ENFORCE_SECURE_PROFILE=${ENFORCE_SECURE_PROFILE:-true}
export ENFORCE_WHITELIST=${ENFORCE_WHITELIST:-false}
export ENTITY_BROADCAST_RANGE_PERCENTAGE=${ENTITY_BROADCAST_RANGE_PERCENTAGE:-100}
export FORCE_GAMEMODE=${FORCE_GAMEMODE:-false}
export FUNCTION_PERMISSION_LEVEL=${FUNCTION_PERMISSION_LEVEL:-2}
export GAMEMODE=${GAMEMODE:-survival}
export GENERATE_STRUCTURES=${GENERATE_STRUCTURES:-true}
export GENERATOR_SETTINGS=${GENERATOR_SETTINGS:-{}}
export HARDCORE=${HARDCORE:-false}
export HIDE_ONLINE_PLAYERS=${HIDE_ONLINE_PLAYERS:-false}
export INITIAL_DISABLED_PACKS=${INITIAL_DISABLED_PACKS:-}
export INITIAL_ENABLED_PACKS=${INITIAL_ENABLED_PACKS:-vanilla}
export LEVEL_NAME=${LEVEL_NAME:-world}
export LEVEL_SEED=${LEVEL_SEED:-}
export LEVEL_TYPE=${LEVEL_TYPE:-minecraft\:normal}
export LOG_IPS=${LOG_IPS:-true}
export MAX_CHAINED_NEIGHBOR_UPDATES=${MAX_CHAINED_NEIGHBOR_UPDATES:-1000000}
export MAX_PLAYERS=${MAX_PLAYERS:-20}
export MAX_TICK_TIME=${MAX_TICK_TIME:-60000}
export MAX_WORLD_SIZE=${MAX_WORLD_SIZE:-29999984}
export MOTD=${MOTD:-A Minecraft Server}
export NETWORK_COMPRESSION_THRESHOLD=${NETWORK_COMPRESSION_THRESHOLD:-256}
export ONLINE_MODE=${ONLINE_MODE:-true}
export OP_PERMISSION_LEVEL=${OP_PERMISSION_LEVEL:-4}
export PLAYER_IDLE_TIMEOUT=${PLAYER_IDLE_TIMEOUT:-0}
export PREVENT_PROXY_CONNECTIONS=${PREVENT_PROXY_CONNECTIONS:-false}
export PVP=${PVP:-true}
export QUERY_PORT=${QUERY_PORT:-25565}
export RATE_LIMIT=${RATE_LIMIT:-0}
export RCON_PASSWORD=${RCON_PASSWORD:-}
export RCON_PORT=${RCON_PORT:-25575}
export REGION_FILE_COMPRESSION=${REGION_FILE_COMPRESSION:-deflate}
export REQUIRE_RESOURCE_PACK=${REQUIRE_RESOURCE_PACK:-false}
export RESOURCE_PACK=${RESOURCE_PACK:-}
export RESOURCE_PACK_ID=${RESOURCE_PACK_ID:-}
export RESOURCE_PACK_PROMPT=${RESOURCE_PACK_PROMPT:-}
export RESOURCE_PACK_SHA1=${RESOURCE_PACK_SHA1:-}
export SERVER_IP=${SERVER_IP:-}
export SERVER_PORT=${SERVER_PORT:-25565}
export SIMULATION_DISTANCE=${SIMULATION_DISTANCE:-10}
export SPAWN_ANIMALS=${SPAWN_ANIMALS:-true}
export SPAWN_MONSTERS=${SPAWN_MONSTERS:-true}
export SPAWN_NPCS=${SPAWN_NPCS:-true}
export SPAWN_PROTECTION=${SPAWN_PROTECTION:-16}
export SYNC_CHUNK_WRITES=${SYNC_CHUNK_WRITES:-true}
export TEXT_FILTERING_CONFIG=${TEXT_FILTERING_CONFIG:-}
export USE_NATIVE_TRANSPORT=${USE_NATIVE_TRANSPORT:-true}
export VIEW_DISTANCE=${VIEW_DISTANCE:-10}
export WHITE_LIST=${WHITE_LIST:-false}

if [ -n "$EULA" ]; then
    echo "eula=true" > eula.txt
fi

envsubst < $MC_BASE/server.properties > /data/server.properties

if [ "$#" -eq 0 ]; then
    exec java ${JAVA_OPTS:--Xms1024m -Xmx1024m} -jar ${SERVER_PATH}
else
    exec "$@"
fi
